package com.example.aslator

import com.auth0.android.jwt.JWT

data class User( val idToken: String? = null ) {

    var id = ""
    var name = ""
    var email = ""

    init {
        try {
            val jwt = JWT(idToken ?: "")
            // JWT = Library used to decode the token generated by Auth0

            id = jwt.subject ?: ""
            name = jwt.getClaim("name").asString() ?: ""
            email = jwt.getClaim("email").asString() ?: ""

        } catch (e: com.auth0.android.jwt.DecodeException) {
            // The ID token is NOT a valid JWT,
            // so leave the user properties as empty strings.
        }
    }
}